### ISSUE TITLE
Data Champion: Explore the Watershed Announcement

### ISSUE THREAD

**Issue by n2parko** [cdr-marketwatch/cdr-fyi-backlog#10]
Submitted from a contact at Aledade: https://watershed.com/blog/frontier-announcement-2

**Comment by kohzy** [comment]
It's not clear from the announcement whether each Watershed customer (or the Watershed consortium) has made any purchases yet as part of this Watershed-Frontier partnership. The language from the [Canva announcement](https://www.canva.com/newsroom/news/canva-partner-watershed-carbon-removal/) in Jan suggests that these customers have made an upfront commitment to participate, but not yet made contributions.

**Comment by kohzy** [comment]
* Added the participating companies as purchasers.
* No specific orders added
