### ISSUE TITLE
Data Champion: Terraset

### ISSUE THREAD

**Issue by n2parko** [cdr-marketwatch/cdr-fyi-backlog#11]
Ensure all data in [this spreadsheet](https://docs.google.com/spreadsheets/d/1agLvAs0yxPBj4XMc9eet3iE9bWFVHHlojRNs3uWGOZ0/edit#gid=0) has been uploaded

**Comment by quentinsl** [comment]
@n2parko I just requested access to the spreadsheet and will work on the upload after that!

**Comment by n2parko** [comment]
Shared! Would filter the orders table by Terraset to see if we have uploaded all orders in the sheet

**Comment by quentinsl** [comment]
@n2parko I'm still getting the `access needed` page would you mind sharing again?

![Uploading image.png…]()

**Comment by quentinsl** [comment]
@n2parko looking by the `purchaser_id`, it appears that the only order we added from Terraset is this 152tons one:

![Image](https://github.com/cdr-marketwatch/cdr-fyi-backlog/assets/43799552/8f7e42e9-b6d7-4058-aa90-028eb1b6cdd0)

which is the top one in the spreadsheet:

![Image](https://github.com/cdr-marketwatch/cdr-fyi-backlog/assets/43799552/c66dba32-e412-4173-bfa0-834679b645fd)

should I go ahead and submit the other orders, even if they don't have the information on the tons that were purchased?

**Comment by n2parko** [comment]
yes, that'd be great 🙏

**Comment by quentinsl** [comment]
All orders that were in the spreadsheet and missing in the db are uploaded, with `null` status

![Image](https://github.com/cdr-marketwatch/cdr-fyi-backlog/assets/43799552/1cb995cc-4945-4f36-ba99-ee71247db51a)

I got the following error originally when submitted with `NULL` tons_purchased and tons_delivered so ended up inputting 0 in both to submit the rows

![Image](https://github.com/cdr-marketwatch/cdr-fyi-backlog/assets/43799552/96d3fe2d-dbaf-4a81-b09f-cea4b37ba75d)

Purchaser_id is `5172f5fd-053b-46a4-b5f3-180912f3ab37` if any update is needed
