### ISSUE TITLE
Bug: Fix the Ørsted supplier page

### ISSUE THREAD

**Issue by quentinsl** [cdr-marketwatch/cdr-fyi-backlog#24]
On the leaderboard of suppliers, clicking on [Ørsted](https://www.cdr.fyi/supplier/orsted) gets to a broken link
https://www.cdr.fyi/supplier/orsted

Flow here:
https://www.loom.com/share/a0c9d682f1184cd981468ac1a255a471

Maybe an issue with special characters?

**Comment by n2parko** [comment]
When new marketplaces/suppliers/buyers are added, we need to kick off a rebuild to build the new page

**Comment by n2parko** [comment]
https://cdr-fyi-r607qaip7-cdr-fyi.vercel.app/supplier/orsted
